# elysian_themes/templates/starship.toml


format = """
╭─\
[](fg:{{ colors.FG_LIGHT }})\
[$os$username](bg:{{ colors.FG_LIGHT }} fg:{{ colors.BG_DARK }})\
[](fg:{{ colors.FG_LIGHT }})\
[ ](fg:{{ colors.FG_DISABLED }})\
$directory\
[](fg:{{ colors.FG_DISABLED }})\
$fill\
$git_branch\
$git_status\
\n╰──\
$character"""

[fill]
symbol = "·"
style = "fg:{{ colors.FG_DISABLED }}"

[character]
success_symbol = "[❯](bold fg:{{ colors.INFO }})"
error_symbol = "[❯](bold fg:{{ colors.ERROR }})"

[os]
disabled = false
style = "bold bg:{{ colors.FG_LIGHT }} fg:{{ colors.BG_DARK }}"

[os.symbols]
Arch = " "
Ubuntu = " "
Fedora = " "
NixOS = " "
Debian = " "
CachyOS = " "

[hostname]
ssh_only = false
trim_at = "."
style = "bold fg:{{ colors.BG_DARK }} bg:{{ colors.FG_LIGHT }}"
format = "[$hostname]($style)"

[username]
show_always = true
format = "[$user](bold bg:{{ colors.FG_LIGHT }} fg:{{ colors.BG_DARK }})"

[directory]
style = "fg:{{ colors.FG }} bg:{{ colors.FG_DISABLED }}"
format = "[󰉖 󱦰 $path]($style)"
truncation_length = 5
truncation_symbol = "../"
home_symbol = "~"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = " "

[git_branch]
symbol = " "
style = "bg:{{ colors.BG_HIGHLIGHT }}"
format = '[](fg:{{ colors.FG_DISABLED }})[[ $symbol$branch ](fg:{{ colors.FG }} bg:{{ colors.FG_DISABLED }})]($style)'

[git_status]
style = "bg:{{ colors.FG_DISABLED }}"
format = '[[($all_status$ahead_behind )](fg:{{ colors.FG }} bg:{{ colors.FG_DISABLED }})]($style)[](fg:{{ colors.FG_DISABLED }})'

[nodejs]
symbol = " "
style = "bg:{{ colors.BG_STRIPE }}"
format = '[[ $symbol ($version) ](fg:{{ colors.FG_DISABLED }} bg:{{ colors.BG_STRIPE }})]($style)'

[rust]
symbol = " "
style = "bg:{{ colors.BG_STRIPE }}"
format = '[[ $symbol ($version) ](fg:{{ colors.FG_DISABLED }} bg:{{ colors.BG_STRIPE }})]($style)'

[golang]
symbol = " "
style = "bg:{{ colors.BG_STRIPE }}"
format = '[[ $symbol ($version) ](fg:{{ colors.FG_DISABLED }} bg:{{ colors.BG_STRIPE }})]($style)'

[php]
symbol = " "
style = "bg:{{ colors.BG_STRIPE }}"
format = '[[ $symbol ($version) ](fg:{{ colors.FG_DISABLED }} bg:{{ colors.BG_STRIPE }})]($style)'

[python]
symbol = " "
style = "bg:{{ colors.BG_STRIPE }}"
format = '[[ $symbol($version) ](bold fg:{{ colors.FG_DISABLED }} bg:{{ colors.BG_STRIPE }})]($style)'
