# yazi/yazi.toml


[opener]
vscodium = [
    { run = 'codium %s', desc = "VSCodium", block = false }
]
nvim = [
    { run = 'nvim %s', block = true }
]
default = [
    { run = 'xdg-open %s', block = false }
]


[open]
rules = [

    ###############
    # DIRECTORIES #
    ###############
    { mime = "inode/directory", use = "nvim" },
    { url = "*/", use = "nvim" },

    ######################
    # JSON / IPYNB RULES #
    ######################
    { url = "*.ipynb", use = "vscodium" },
    { mime = "application/json", use = "nvim" },

    ##############
    # TEXT FILES #
    ##############
    { mime = "text/*", use = "nvim" },
    
    #############################
    # OTHER APPLICATION/* FILES #
    #############################
    { mime = "application/octet-stream", use = "nvim" },

    ###########
    # SVG+XML #
    ###########
    { mime = "image/svg+xml", use = "nvim" },

    ###########
    # DEFAULT #
    ###########
    { mime = "*/*", use = "default" }
]
