[opener]
vscodium = [
    { run = 'codium "$@"', desc = "VSCodium", block = false }
]
nvim = [
    { run = 'nvim "$@"', block = true }
]
default = [
    { run = 'xdg-open "$@"', block = false }
]


[open]
rules = [

    ######################
    # JSON / IPYNB RULES #
    ######################
    { name = "*.ipynb", use = "vscodium" },
    { name = "*.json", use = "nvim" },

    ##############
    # PLAIN TEXT #
    ##############
    { mime = "text/plain", use = "nvim" },

    ###########
    # DEFAULT #
    ###########
    { mime = "*/*", use = "default" }
]


[[bookmark]]
name = "Dotfiles"
path = "~/Dotfiles/"
key = "d"

