# hypr/hyprland.conf


# --- LOAD ACTIVE ELYSEAN THEME --------------------- #
source = ~/.config/elysean_themes/active_theme.conf

# --- LOAD VARIABLES (DEFAULT AND/OR CUSTOM) -------- #
source = ~/.config/hypr/default/variables.conf
source = ~/.config/hypr/user/variables.conf

# --- LOAD DEFAULT CONFIGURATION -------------------- #
source = ~/.config/hypr/default/env.conf
source = ~/.config/hypr/default/monitors.conf
source = ~/.config/hypr/default/look-and-feel.conf
source = ~/.config/hypr/default/input.conf
source = ~/.config/hypr/default/keybinds.conf
source = ~/.config/hypr/default/windowrules.conf
source = ~/.config/hypr/default/autostart.conf


# --- LOAD USER OVERRIDES --------------------------- #
source = ~/.config/hypr/user/env.conf
source = ~/.config/hypr/user/monitors.conf
source = ~/.config/hypr/user/look-and-feel.conf
source = ~/.config/hypr/user/input.conf
source = ~/.config/hypr/user/keybinds.conf
source = ~/.config/hypr/user/windowrules.conf
source = ~/.config/hypr/user/autostart.conf
