# quickshell/themes/default/WitcherTokyoNight.conf


# Only works for images inside the quickshell/assets/wallpapers directory
WALLPAPER_PATH=Witcher.jpg

COLOR_1=7dcfff
COLOR_2=7aa2f7
COLOR_3=bb9af7
COLOR_4=9ece6a
COLOR_5=ff9e64
COLOR_6=1a3a5c
COLOR_7=1f2335
