# quickshell/themes/default/WitcherTokyoNight.conf


WALLPAPER_PATH=~/.config/quickshell/assets/wallpapers/Witcher.jpg

# Base UI
BG=0x1a1b26
BG_DARK=0x16161e
BG_HIGHLIGHT=0x292e42
TERMINAL_BLACK=0x414868
FG=0xc0caf5
FG_DARK=0xa9b1d6
FG_GUTTER=0x3b4261
DARK3=0x545c7e
DARK5=0x737aa2
COMMENT=0x565f89

# Syntax / Accent
BLUE=0x7aa2f7
CYAN=0x7dcfff
BLUE1=0x2ac3de
BLUE2=0x0db9d7
BLUE5=0x89ddff
BLUE6=0xb4f9f8
BLUE7=0x394b70
MAGENTA=0xbb9af7
MAGENTA2=0xff007c
PURPLE=0x9d7cd8
ORANGE=0xff9e64
YELLOW=0xe0af68
GREEN=0x9ece6a
GREEN1=0x73daca
GREEN2=0x41a6b5
TEAL=0x1abc9c
RED=0xf7768e
RED1=0xdb4b4b
