# default/autostart.conf



# --- AUTO START CONFIGURATION --------------------------- #

exec-once   =   dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once   =   eww open topbar
exec-once   =   quickshell
exec-once   =   dunst
