# default/monitors.conf



# --- MONITORS CONFIGURATION --------------------------- #

# See https://wiki.hypr.land/Configuring/Monitors/ for more


# Monitor resolution, refresh rate and scaling
monitor =   ,   $monitor_res,   auto,   $monitor_scale


# XWayland settings
xwayland {
    force_zero_scaling  =   true
}
