# Elysian Dark Theme for btop
# Based on Elysian (Nord + Tokyo Night fusion) by quisiou

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0d0f12"

# Main text color
theme[main_fg]="#eceff4"

# Title color for boxes
theme[title]="#2ac3de"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#88c0d0"

# Background color of selected items
theme[selected_bg]="#1c212a"

# Foreground color of selected items
theme[selected_fg]="#2ac3de"

# Color of inactive/disabled text
theme[inactive_fg]="#2e3440"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#434c5e"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#9ece6a"

# Cpu box outline color
theme[cpu_box]="#d8dee9"

# Memory/disks box outline color
theme[mem_box]="#d8dee9"

# Net up/down box outline color
theme[net_box]="#d8dee9"

# Processes box outline color
theme[proc_box]="#d8dee9"

# Box divider line and small boxes line color
theme[div_line]="#434c5e"

# Temperature graph colors
theme[temp_start]="#2ac3de"
theme[temp_mid]="#1abc9c"
theme[temp_end]="#88c0d0"

# CPU graph colors
theme[cpu_start]="#9ece6a"
theme[cpu_mid]="#bb9af7"
theme[cpu_end]="#ff96f8"

# Mem/Disk free meter
theme[free_start]="#2ac3de"
theme[free_mid]=""
theme[free_end]="#1abc9c"

# Mem/Disk cached meter
theme[cached_start]="#88c0d0"
theme[cached_mid]=""
theme[cached_end]="#7dcfff"

# Mem/Disk available meter
theme[available_start]="#9ece6a"
theme[available_mid]=""
theme[available_end]="#bb9af7"

# Mem/Disk used meter
theme[used_start]="#ff96f8"
theme[used_mid]=""
theme[used_end]="#fc7b7b"

# Download graph colors
theme[download_start]="#2ac3de"
theme[download_mid]="#1abc9c"
theme[download_end]="#88c0d0"

# Upload graph colors
theme[upload_start]="#ff96f8"
theme[upload_mid]="#fc7b7b"
theme[upload_end]="#bb9af7"
